[build]
  command = "npm run build && cd server && npm install && npm run build"
  publish = "build"
  functions = "server/functions"

# Handle client-side routing with React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Proxy API requests to serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  node_bundler = "esbuild"