[build]
  command = "npm run build && cd server && npm install && npm run build"
  publish = "build"
  functions = "server/functions"

# Handle client-side routing with React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Enable socket.io websocket connections
[[redirects]]
  from = "/socket.io/*"
  to = "/.netlify/functions/socket-server/:splat"
  status = 200
  force = true

# Proxy API requests to serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  node_bundler = "esbuild"
  # Set maximum function execution time to 10 seconds (the maximum on Netlify)
  included_files = ["server/dist/**"]
  # Configure socket-server function specifically
  [functions."socket-server"]
    timeout = 10
  
[dev]
  framework = "#custom"
  command = "npm start"
  port = 3000
  targetPort = 3000
  publish = "build"